### ISSUE TITLE
Host a distributed 'Procurement Camp' day where people can connect in-person to brainstorm/collaborate on government procurement solutions

### ISSUE THREAD

**Issue by lukefretwell** [Procurementeers/ideas#2]

**Comment by waldoj** [comment]
Sure seems like a fun idea to me.

**Comment by kaitlin** [comment]
Weeeee! 🎉  Count me in

**Comment by mgifford** [comment]
In DC? Any options for remote connections?

**Comment by lukefretwell** [comment]
@mariel-reed @waldoj @kaitlin @mgifford closing this issue and moving the convo to its own repo:

https://github.com/Procurementeers/procurement-camp

Feel free to add ideas and/or how you'd like to participate:

https://github.com/Procurementeers/procurement-camp/issues

Let's go!
